# Don't change this
theme: jekyll-theme-primer
spec_server: specs.amwa.tv

# AMWA ID
amwa_id: AS-11_X6

# Base name for site (typically lower case version of AMWA ID, or the repo name)
baseurl: /as-11_x6

# Which release or branch appears in header links and on the home page
default_tree: branches/master

# Regex patterns of releases and branches to show
show_releases: 
show_branches: ^master$|^main$|^publish-
